/*
 * This file was generated by the Gradle 'init' task.
 * These build tasks are separated from maven due to an
 * incompatability between the helper plugins and
 * the project code
 */

plugins {
    id("ru.vyarus.mkdocs") version "4.0.1"
}

repositories {
    mavenCentral()
}
