site_name: Spring Into Computer Science

# Meta tags (placed in header)
site_description: Learn Java Spring
site_author: Kurt Sell
site_url: https://github.com/ksell8/spring-tutorial

# Repository (add link to repository on each page)
repo_name: spring-tutorial
repo_url: https://github.com/ksell8/spring-tutorial
edit_uri: edit/main/src/doc/docs/

#Copyright (shown at the footer)
copyright: 'Copyright &copy; 2024 Kurt Sell'

# Meterial theme
theme:
  name: 'material'
  palette:
    primary: 'green'
    accent: 'light-green'
    scheme: slate
  features:
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.footer

plugins:
  - search
#    Required for variables support (https://github.com/rosscdh/mkdocs-markdownextradata-plugin)
#  - markdownextradata

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ksell8


markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Learn:
      - Computer Science Basics:
        - Computing Languages: learn/general/languages.md
        - Operating Systems: learn/general/os.md
        - Networking Protocols & Routing: learn/general/networking.md
        - Applications: learn/general/applications.md
        - Licensing: learn/general/licensing.md
      - Java:
        - History of Java: learn/java/history.md
        - JiT Compilation & the JVM: learn/java/jit.md
        - Garbage Collection: learn/java/garbage.md
        - Spring:
          - Inversion of Control and Dependency Injection: learn/java/spring/containers.md
          - Spring Boot Annotations: learn/java/spring/annotations.md
          - Spring Beans & Other Annotations: learn/java/spring/spring-beans.md
        - Maven:
          - Java Build Systems: learn/java/maven/build.md
          - Basic Maven Configuration: learn/java/maven/basic.md
          - Packaging: learn/java/maven/packaging.md
          - Plugins: learn/java/maven/plugins.md
      - Docker:
        - Virtualization & Containers: learn/docker/containers.md
        - Docker Concepts & Related Commands: learn/docker/docker.md
        - Docker Compose & Container Orchestration: learn/docker/docker-compose.md
        - Docker Volumes: learn/docker/volumes.md
      - MongoDB:
        - Relational vs Non-Relational Databases: learn/mongodb/sql.md
        - JSON: learn/mongodb/bson.md
        - MongoDB Driver: learn/mongodb/driver.md
      - GraphQL:
        - Schemas: learn/graphql/schema.md
        - Queries & Mutations: learn/graphql/query-mutation.md
        - GraphQL-Spring: learn/graphql/spring.md
  - Tutorial:
      - Install Tools: tutorial/installation.md
      - Generate Base Project: tutorial/base.md
      - Generate GraphQL Schema: tutorial/schema.md
      - Create Scalar Support: tutorial/scalar.md
      - Add Repository & Data Fetchers and Mutators: tutorial/data.md
      - Write Tests: tutorial/tests.md
      - Add Docker Infrastructure: tutorial/docker.md
      - Logging & Error Handling: tutorial/logging.md
  - About:
      - Release notes: about/history.md
      - Site Info: about/site.md